name: Build Docker Image

# 当 push 到 master 分支，或者创建以 v 开头的 tag 时触发，可根据需求修改
on:
  push:
    branches:
      - master
  schedule:
    # 每周二早上10点运行
    - cron: '0 10 * * 2'

env:
  REGISTRY: ghcr.io
  IMAGE: liziwl/texlive-full-with-fonts

jobs:
  build-and-push:
    name: "Build and push ghcr images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        texlive: [latest, TL2021-historic, TL2020-historic, TL2019-historic]
        # 多版本 TexLive
        # 版本号选自：https://hub.docker.com/r/texlive/texlive/tags
    permissions:
      # 这里用于定义 GITHUB_TOKEN 的权限
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 登录到 GitHub Packages 容器仓库
      # 注意 secrets.GITHUB_TOKEN 不需要手动添加，直接就可以用
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 根据输入自动生成 tag 和 label 等数据，说明见下
      - name: Extract metadata for Container
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: ${{ matrix.texlive }}

      # 构建并上传
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TEXLIVE_TAG=${{ matrix.texlive }}

      - name: Inspect image
        run: |
          docker buildx imagetools inspect \
          ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.meta.outputs.version }}

  clean-untagged-images:
    name: "Clean untagged images"
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Delete all containers from repository without tags
        continue-on-error: true
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
            token: ${{ secrets.PAT_TOKEN }}
            repository_owner: ${{ github.repository_owner }}
            repository: ${{ github.repository }}
            untagged_only: true
            owner_type: user
